repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--diff"]
        exclude: ^migrations/
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--check-only"]
        exclude: ^migrations/
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--ignore=E501,W503"]
        exclude: ^migrations/
