[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "simplex"
FLASK_ADMIN_NAME = "Flapp"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "flapp.ext.db:init_app",
    "flapp.ext.site:init_app",
    "flapp.ext.cli:init_app",
    "flapp.ext.admin:init_app"
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///flapp.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
FLASK_ADMIN_NAME = "Flapp (dev mode)"
EXTENSIONS = [
    "flapp.ext.db:init_app",
    "flapp.ext.site:init_app",
    "flapp.ext.cli:init_app",
    "flapp.ext.admin:init_app",
    "flask_debugtoolbar:DebugToolbarExtension"
]

[test]
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
